name: PR Checks

on:
  pull_request:
    branches:
      - main # or the default branch you use
    paths:
      - "**/*.js" # specify which files or paths to monitor (optional)
      - "**/*.ts"
      - "**/*.tsx"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Run Linting
        run: npm run lint # run lint command (lint script defined in package.json)

  test:
    runs-on: ubuntu-latest
    needs: lint # Ensure linting passes before running tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm test # run test command (test script defined in package.json)

  build:
    runs-on: ubuntu-latest
    needs: test # Ensure tests pass before building
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build # run build command (build script defined in package.json)

